### ISSUE TITLE
django app fail

### ISSUE THREAD

**Issue by ATouhou** [Alfanous-team/alfanous#463]
Assalamu aleykoum wa rahmatullahi wa barakatuh my beloved brothers.
I just tried setting it up localhost and after a whole bunch of problems (there is a lot extra things that has to be installed that is not listed in your walkthrough/guide"),  I get this error:

![image](https://cloud.githubusercontent.com/assets/6802820/13383200/5970f40e-de86-11e5-8e1c-6048d7df807d.png)

any ideas?

**Comment by assem-ch** [comment]
Salam,  welcome

Please feel free to add the libs that not listed to the hotwto so other people will find it listed. 

For the error, it means the app didnt find the indexes.  A possible cause for this is that you didnt run: 

     $ make build

Another possible cause is a conflict between installed version of alfanous and the one in the source repo.

**Comment by ATouhou** [comment]
Yes I did not "make build", as it is not the right command.. (not recognized on windows, and I installed Sphinx). I will try to add the different steps for windows in Sha Allah if I do clean install on another pc in Sha Allah

**Comment by assem-ch** [comment]
If you are going to use only the django app, I suggest to install  alfanous api using pip:

     $ pip install alfanous

In this case, you should comment those 3 lines (30-32):
https://github.com/Alfanous-team/alfanous/blob/master/src/alfanous-django/wui/views.py#L30

**Comment by ATouhou** [comment]
Yes works great doing that. 
I'm most proficient in PHP, JS, HTML and CSS, so I don't know how much benefitting I can do you.                     How do "make build", so that everything will work?

**Comment by assem-ch** [comment]
You may help in [web-labeled ](https://github.com/Alfanous-team/alfanous/labels/web) issues, I would suggest:
- [ ] Printability of the website #395 
- [ ] Floating-panel with options and user feedback for clickable-tags #132
- [ ] Make Every tag draggable into an extra search input  #214 
- [ ] Create scripts for embedding Ayahs or Search results in third party websites #118

I used to run `make build` in windows using the shell installed within Github-for-desktop,  its tricky but worked for me. Another solution is to run it in a linux machine and than copy it to your machine, I can give you an account to copy the version running on the web server.

**Comment by sneetsher** [comment]
Well there other alternatives packages for `autotools` in MS Windows like: 

- http://www.mingw.org/
- https://sourceforge.net/projects/getgnuwin32/

But as you are a developer you may want all dev tools ready at hand, so i recommend instead:

- https://www.cygwin.com/ 

      It has a large collection of GNU and Open Source tools which provide functionality similar to a Linux distribution on Windows.
